### PR TITLE
Add Provides tag for user and groups

### PR DESCRIPTION
**Pull request by thardeck**
Following the guide https://en.opensuse.org/openSUSE:Packaging_guidelines#Users_and_Groups
as requested by our security team.

### CODE REVIEW

**Comment by dgoetz** [comment]
This is not used by Fedora/RHEL and so should be tested if it is simply ignored or causes problems on these distributions.

**Comment by thardeck** [comment]
It does seem to build fine against CentOs 7, can not judge older versions.

**Comment by dnsmichi** [comment]
Should be made SLES specific imho.

**Comment by thardeck** [comment]
It seems that we are configuring the /var/run/icinga2 partly in the spec file, although it must be recreated on each start on modern systems if I remember correctly.

Is this done by the systemd unit file? If so, why do we add it to the spec file then with quite a lot of logic?

The reason I ask is the following is that the security team asked me to add this https://en.opensuse.org/openSUSE:Systemd_packaging_guidelines#Creating_files_.2F_subdirectories_in_.2Fvar.2Frun_and_.2Frun . But maybe it is not needed and we can clean up the logic quite a bit.

**Comment by thardeck** [comment]
Would you be open for a change like this:
```
icinga2-common.x86_64: W: suse-logrotate-user-writable-log-dir /var/log/icinga2 icinga:icingacmd 0750 The log directory is writable by unprivileged users. Please fix the permissions so only root can write there or add the 'su' option to your logrotate config
```

**Comment by dgoetz** [comment]
Yes, we should set 'su' in the logrotate config then.

**Comment by thardeck** [comment]
@dgoetz Thx. Will this be part of the next release?

**Comment by dgoetz** [comment]
If I understand https://github.com/Icinga/icinga2/commit/4970c459ee9fa09c4ab92a2553824f2586fb77f5 correctly it should already be there, but I think the spec is missing logrotate as buildrequires for this fix to work. 

Should I create a separate PR for this?

**Comment by thardeck** [comment]
@dgoetz You are right, adding this as a buildrequires works. I can add it to this pr. Should I only add it for SUSE distributions or in general?

**Comment by dnsmichi** [comment]
This PR is about tags, should be split imho.

**Comment by thardeck** [comment]
@dgoetz I can create one if I know for which distribution to add it.

**Comment by dgoetz** [comment]
@thardeck: Thanks, I would suggest adding it to all distributions as I am not aware of any problem this could cause.

**Comment by thardeck** [comment]
Done: https://github.com/Icinga/icinga-packaging/pull/76

**Comment by thardeck** [comment]
Are the changes ok?

**Comment by thardeck** [comment]
Icinga2 was accepted into openSUSE Factory so it would be great if you could also merge these changes.

If any change is needed let me know.

**Comment by thardeck** [comment]
@dgoetz any update on this?

**Comment by dgoetz** [comment]
@lazyfrosch: I am fine with the changes, should the commits be squashed or something else before this is merged?

**Comment by lazyfrosch** [comment]
@thardeck sorry for late feedback, thank you!

**Pull request merged**
