### PR TITLE
Incorporate changes for openSUSE Leap 15 submit request

### PR DESCRIPTION
**Pull request by thardeck**
We are trying to get Icinga2 in openSUSE Leap 15. For this the following changes were requested.

I hope that most of the changes will be universal so we can keep our rpm spec mostly in sync.

Let me know if anything is debatable so I can forward it.

### CODE REVIEW

**Comment by dgoetz** [comment]
From Fedora guidelines Group should not be used at all, so no problem changing this.
Changing the wording of the description of the subpackages is fine for me, too.
Fedora guidelines also recommend to hav no %clean section.

**Comment by thardeck** [comment]
Is anything else needed, like a bug report or similar?

**Comment by dnsmichi** [comment]
Since PRs act as issue with review possibilities, you don't need an extra issue :)

**Comment by thardeck** [comment]
More changes are required to get the package into openSUSE Leap and Tumbleweed.

"There are too many serious rpmlint warnings. This should have a devel package for the .so files and separate doc package."

The concrete warnings are:
```
[  440s] icinga2-common.x86_64: W: package-with-huge-docs  53%
[  440s] icinga2-bin.x86_64: W: package-with-huge-docs  55%
[  440s] More than half the size of your package is documentation. Consider splitting
[  440s] it into a -doc subpackage.
```

```
[  440s] icinga2-libs.x86_64: E: devel-file-in-non-devel-package (Badness: 50) /usr/lib64/icinga2/libbase.so
[  440s] icinga2-libs.x86_64: E: devel-file-in-non-devel-package (Badness: 50) /usr/lib64/icinga2/libchecker.so
[  440s] icinga2-libs.x86_64: E: devel-file-in-non-devel-package (Badness: 50) /usr/lib64/icinga2/libcli.so
[  440s] icinga2-libs.x86_64: E: devel-file-in-non-devel-package (Badness: 50) /usr/lib64/icinga2/libcompat.so
[  440s] icinga2-libs.x86_64: E: devel-file-in-non-devel-package (Badness: 50) /usr/lib64/icinga2/libconfig.so
[  440s] icinga2-libs.x86_64: E: devel-file-in-non-devel-package (Badness: 50) /usr/lib64/icinga2/libdb_ido.so
[  440s] icinga2-ido-mysql.x86_64: E: devel-file-in-non-devel-package (Badness: 50) /usr/lib64/icinga2/libdb_ido_mysql.so
[  440s] icinga2-ido-pgsql.x86_64: E: devel-file-in-non-devel-package (Badness: 50) /usr/lib64/icinga2/libdb_ido_pgsql.so
[  440s] icinga2-libs.x86_64: E: devel-file-in-non-devel-package (Badness: 50) /usr/lib64/icinga2/libexecvpe.so
[  440s] icinga2-libs.x86_64: E: devel-file-in-non-devel-package (Badness: 50) /usr/lib64/icinga2/libicinga.so
[  440s] icinga2-libs.x86_64: E: devel-file-in-non-devel-package (Badness: 50) /usr/lib64/icinga2/liblivestatus.so
[  440s] icinga2-libs.x86_64: E: devel-file-in-non-devel-package (Badness: 50) /usr/lib64/icinga2/libmethods.so
[  440s] icinga2-libs.x86_64: E: devel-file-in-non-devel-package (Badness: 50) /usr/lib64/icinga2/libmmatch.so
[  440s] icinga2-libs.x86_64: E: devel-file-in-non-devel-package (Badness: 50) /usr/lib64/icinga2/libnotification.so
[  440s] icinga2-libs.x86_64: E: devel-file-in-non-devel-package (Badness: 50) /usr/lib64/icinga2/libperfdata.so
[  440s] icinga2-libs.x86_64: E: devel-file-in-non-devel-package (Badness: 50) /usr/lib64/icinga2/libremote.so
[  440s] icinga2-libs.x86_64: E: devel-file-in-non-devel-package (Badness: 50) /usr/lib64/icinga2/libsocketpair.so
[  440s] A file that is needed only e.g. when developing or building software is
[  440s] included in a non-devel package. These files should go in devel packages.
```

A solution would be to put the so files in an `icinga2-devel` package and the common doc files in the already existing `icinga2-doc` or a separate doc package.

Would this be something you would consider or should I not try to change it?

**Comment by dnsmichi** [comment]
Those docs warnings ... how do they calculate their percentage?

In terms of devel packages ... lib*.so are NOT development binaries, they are libraries loaded by the icinga2 application. Why does that warning happen?

**Comment by thardeck** [comment]
Thx for your quick reply. I have asked them about it.

The check might be not that sophisticated, but it often helps package maintainers quite a bit to find issues.

I will disable the `devel-file-in-non-devel-package` check and wait for a response.

**Comment by thardeck** [comment]
There is one last thing reported as error from rpmlint. Would it be worth to create a pr for this or do you prefer using env?

I also wonder why they do not adapt the package dependency generator.
```
[  348s] icinga2-common.x86_64: E: env-script-interpreter (Badness: 9) /etc/icinga2/scripts/mail-host-notification.sh /usr/bin/env bash
[  348s] icinga2-common.x86_64: E: env-script-interpreter (Badness: 9) /etc/icinga2/scripts/mail-service-notification.sh /usr/bin/env bash
[  348s] This script uses 'env' as an interpreter. For the rpm runtime dependency
[  348s] detection to work, the shebang #!/usr/bin/env python  needs to be patched into
[  348s] #!/usr/bin/python  otherwise the package dependency generator merely adds a
[  348s] dependency on /usr/bin/env rather than the actual interpreter /usr/bin/python.
[  348s] Alternatively, if the file should not be executed, then ensure that it is not
[  348s] marked as executable or don't install it in a path that is reserved for
[  348s] executables.
```

**Comment by dnsmichi** [comment]
Upstream will keep /usr/bin/env, that is a common sensible default.

**Comment by thardeck** [comment]
Ok, so I will report his against rpmlint. I think they should adapt the filter.

**Comment by thardeck** [comment]
@dnsmichi Many thanks for your quick feedback. The review got accepted and not further changes are needed so far. As far as I know only a security review is missing before the package will end up in openSUSE Tumbleweed and later in Leap 15.

**Comment by thardeck** [comment]
Would the changes as they are be ok from your side?

**Comment by thardeck** [comment]
Should I create a new pr against the latest changes? These merge conflicts are not that easy to read.

**Comment by lazyfrosch** [comment]
I will rebase your branch, like the changes so far.

We did some selinux changes as well, I will send them in on OBS...

**Comment by lazyfrosch** [comment]
@thardeck thanks for your work.

Please see https://build.opensuse.org/request/show/545236

**Pull request merged**
