### PR TITLE
Allow building of the icinga2 package against openSUSE on OBS

### PR DESCRIPTION
**Pull request by thardeck**
refs #5530

### CODE REVIEW

**Comment by lazyfrosch** [comment]
Thanks @thardeck, a few notes:

* We need the changelog for our history system, so it's not likely to go away here :)
* I'm wondering why the missing `%dir` seems only to be an issue on OBS

 @dgoetz: Should we add `%dir` for RedHat based systems too?

**Comment by dgoetz** [comment]
@lazyfrosch: No, we should not own this directories on Red Hat derivates as only one package should own these directories and all this packages are listed as dependencies.

**Comment by lazyfrosch** [comment]
I'm wondering why we should own them on SuSE?

**Comment by thardeck** [comment]
@lazyfrosch 
```
[  532s] ... checking filelist
[  532s] vim-icinga2-2.7.0-1.x86_64.rpm: directories not owned by a package:
[  532s]  - /usr/share/vim
[  532s]  - /usr/share/vim/vim74
[  532s]  - /usr/share/vim/vim74/ftdetect
[  532s]  - /usr/share/vim/vim74/syntax
[  532s] nano-icinga2-2.7.0-1.x86_64.rpm: directories not owned by a package:
[  532s]  - /usr/share/nano
```

An alternative would be to install vim and nano during build so their is no confusion about which files and dirs belong to which package.

**Comment by thardeck** [comment]
I wonder why the build system does not install the requirements before the tests because you do require `vim-data`.

**Comment by dnsmichi** [comment]
I would remove the history from the spec file, this was removed for the exact reason in the past not to run into linting troubles or wrong updates here. I'm not sure why it was added for v2.7.0 again.

**Comment by thardeck** [comment]
@dgoetz 
If you prefer it I can change the spec to add the BuildRequire for `vim-data` and `nano` on SUSE systems.

**Comment by dgoetz** [comment]
@thardeck: Instead of adding it as build requirement, is simply creating the directories enough? It seems vim and nano are installed by default on Red Hat derivates (even in minimal build environments), so it is not necessary there, but would not hurt, too. We already recognized in an early fix that build environments in OBS seems to include less than expected (or our build systems).

**Comment by lazyfrosch** [comment]
Testing some changes on:
https://build.opensuse.org/package/rdiff/home:lazyfrosch:icinga2/icinga2?opackage=icinga2&oproject=server%3Amonitoring&rev=2

**Comment by thardeck** [comment]
@lazyfrosch I can built it locally, that is much faster. Let me know which change you prefer and then I can adapt and built it.

**Comment by lazyfrosch** [comment]
@thardeck I've updated your commits, hope you don't mind.

I also submitted https://build.opensuse.org/request/show/518671

**Comment by lazyfrosch** [comment]
One more small change... `>=` instead of `>`

**Comment by thardeck** [comment]
@lazyfrosch Sure it is fine.
I think the build will fail because the dirs like `%{_datadir}/vim/site/syntax/` are not part of the package.

**Comment by lazyfrosch** [comment]
@thardeck they are within the vim package, which has been added as require and buildrequire. It built fine previously

Sadly the OBS does not utilize `Requires` for that check. I guess because of the `lib*-dev` installs `lib*` idea...

https://build.opensuse.org/request/show/518676

**Comment by thardeck** [comment]
I think the `suse_version` check for Leap needs to be changed to ` %if 0%{?leap_version} >= 420100` 
https://en.opensuse.org/openSUSE:Build_Service_cross_distribution_howto

I have asked about the reason why `Requires` are not pulled in and the issue is that for more complicated package it would be so many packages which would be pulled in during build time just for running the installation/file matching test.

**Comment by lazyfrosch** [comment]
Good point regarding requires. More BuildRequires then :)

Will change to leap_version once the build completes... Can I update the request on OBS to a new revision, or do I have to revoke it?

**Comment by thardeck** [comment]
I think you can only supersede it. If you submit the updated package it show the old one in a dialog and you can mark it a superseded.

**Comment by thardeck** [comment]
@lazyfrosch I have resubmitted your pr and merged it, sadly it seems there is no package nano on s390x, ppc64le and aarch64.

**Comment by lazyfrosch** [comment]
@thardeck I guess you would have to setup an exception for the nano package then, but that should be OBS specific :wink: 

Merging the current changes here!

**Comment by lazyfrosch** [comment]
@thardeck Thanks for your support!

**Comment by thardeck** [comment]
It even breaks on all SLES  architectures because there is no nano. I will look into it.

**Pull request merged**
